
//Cart
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_FETCHING = 'ADD_TO_CART_FETCHING'
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'


//Edit Cart
export const EDIT_CART_REQUEST = 'EDIT_CART_REQUEST'
export const EDIT_CART_FETCHING = 'EDIT_CART_FETCHING'
export const EDIT_CART_FAILED = 'EDIT_CART_FAILED'
export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS'
